linters:
  disable-all: true
  enable:
    - copyloopvar
    - errcheck
    - gocritic
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - usestdlibvars

linters-settings:
  goimports:
    local-prefixes: github.com/simplesurance/grpcconsulresolver
