linters:
  disable-all: true
  enable:
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - godox
    - gofumpt
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - prealloc
    - revive
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - usestdlibvars

linters-settings:
  gofumpt:
    module-path: github.com/simplesurance/grpcconsulresolver
    extra-rules: true
  godox:
    keywords:
      - FIXME
