linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - goimports
    - revive
    - gosimple
    - ineffassign
    - misspell
    - rowserrcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - vet

linters-settings:
  goimports:
    local-prefixes: github.com/simplesurance/grpcconsulresolver
